In [48]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import pymysql
import sqlite3

In [49]:
mydb = pymysql.connect(
    host="localhost",
    user="root",
    password="",
    database="fastfood",
    charset="utf8"
)

In [50]:
Ratings = pd.read_sql_query(
    "SELECT ten_kh,ten_mon_an,diem_dg  FROM khach_hang,`binh_luan_danh_gia`,mon_an where mon_an.id_mon_an=binh_luan_danh_gia.id_mon_an and khach_hang.id_kh=binh_luan_danh_gia.id_kh", mydb)
print(Ratings)

                 ten_kh           ten_mon_an  diem_dg
0        Nguyễn Văn Nam          Nước ép dâu        5
1        Nguyễn Văn Nam    Khoai lắc xí muội        3
2        Nguyễn Văn Nam      Cơm Gà Xiên Que        1
3        Nguyễn Văn Nam       Aquafina 500ml        5
4        Nguyễn Văn Nam         Combo cơm gà        3
5        Nguyễn Văn Nam             Milo Hộp        4
6        Nguyễn Văn Nam         Combo Nhóm 1        5
7    Nguyễn Võ Khánh My  3 Cánh Gà Hot Wings        5
8    Nguyễn Võ Khánh My             Milo Hộp        5
9        Nguyễn Văn Anh       Aquafina 500ml        5
10       Nguyễn Văn Anh   2 Thanh Bí Phô Mai        4
11      Nguyễn Khánh Ly          Nước ép dâu        4
12      Nguyễn Khánh Ly                Pepsi        1
13      Nguyễn Khánh Ly          Nước ép cam        1
14      Nguyễn Khánh Ly         Combo Nhóm 1        5
15      Nguyễn Khánh Ly    Khoai lắc xí muội        3
16      Nguyễn Khánh Ly   2 Thanh Bí Phô Mai        4
17      Nguyễn Khánh Ly      Cơm Gà Xiên Que        5
18            Lê Văn Bi              7Up Lon        4
19            Lê Văn Bi   2 Thanh Bí Phô Mai        2
20    Nguyễn Hoàng Minh          Nước ép dâu        5
21                Ly Ly         Combo cơm gà        2
22                Ly Ly          Nước ép dâu        3
23  Lý Nguyễn Trọng Tín   2 Thanh Bí Phô Mai        5
24  Lý Nguyễn Trọng Tín              7Up Lon        5
25  Lý Nguyễn Trọng Tín    Khoai lắc xí muội        5
26  Lý Nguyễn Trọng Tín         4 Bánh Trứng        5
27  Lý Nguyễn Trọng Tín             Milo Hộp        3
28  Lý Nguyễn Trọng Tín                Pepsi        4
29  Lý Nguyễn Trọng Tín          Nước ép dâu        5
30  Lý Nguyễn Trọng Tín  3 Cánh Gà Hot Wings        5
31      Nguyễn Hải Đăng  3 Cánh Gà Hot Wings        5
32      Nguyễn Hải Đăng              7Up Lon        5

c:\Users\lmhai\anaconda3\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [51]:
items = pd.read_sql_query(
    "SELECT id_mon_an, ten_mon_an FROM `mon_an`", mydb)
print(items)

    id_mon_an                    ten_mon_an
0          30                   Nước ép cam
1          31                   Nước ép dâu
2          35                       Nui xào
3          37                         Pepsi
4          39             Khoai lắc xí muội
5          42                  Combo cơm gà
6          43                  Combo Nhóm 1
7          44               Cơm Gà Xiên Que
8          46                  1 Bánh Trứng
9          48            2 Thanh Bí Phô Mai
10         49                  4 Bánh Trứng
11         50            5 Thanh Bí Phô Mai
12         51                       7Up Lon
13         52                Aquafina 500ml
14         53                       Trà Đào
15         54          Pepsi Black Lime Lon
16         55                      Milo Hộp
17         56               Mirinda Cam Lon
18         57                 Burger Zinger
19         58                    Burger Tôm
20         59          Burger Gà Quay Flava
21         60         Cơm Xiên Gà Tenderods
22         61               Cơm Gà Teriyaki
23         62                Cơm Gà Bít-tết
24         63         Gà Bít-tết với Khoai
25         64  Mì Ý Xốt Cà Xúc Xích Gà Viên
26         65            Mì Ý Xốt Gà Zinger
27         66                    Cơm Gà Rán
28         67            Cơm Phi-lê Gà Quay
29         68                  Miếng Gà Rán
30         69                2 Miếng Gà Rán
31         70                6 Miếng Gà Rán
32         71             Miếng Đùi Gà Quay
33         72               Miếng Phi-lê Gà
34         73           3 Cánh Gà Hot Wings
35         74           5 Cánh Gà Hot Wings
36         75                    3 Cá Thanh
37         76                    2 Xiên Que
38         77              2 Xiên Tenderods
39         78                4 Phô Mai Viên
40         79                6 Phô Mai Viên
41         80         3 Mashies Nhân Rau Củ
42         81         5 Mashies Nhân Rau Củ
43         82                 Súp Rong Biển
44         83                    Súp Rau Củ
45         84         Khoai Tây Chiên (Vừa)
46         85         Khoai Tây Chiên (Lớn)
47         86         Khoai Tây Chiên (Đại)
48         88        Khoai Tây Nghiền (Vừa)
49         89        Khoai Tây Nghiền (Lớn)
50         90        Khoai Tây Nghiền (Đại)
51         91                  Combo Nhóm 2
52         92                  Combo Nhóm 3
53         93                Combo Gia Đình

c:\Users\lmhai\anaconda3\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [52]:
users = pd.read_sql_query(
    "SELECT id_kh,ten_kh FROM khach_hang", mydb)
print(users)

   id_kh                ten_kh
0      1        Nguyễn Văn Nam
1     13    Nguyễn Võ Khánh My
2     14  Nguyễn Võ Khánh Linh
3     15        Nguyễn Văn Anh
4     16       Nguyễn Khánh Ly
5     17             Lê Văn Bi
6     18     Nguyễn Hoàng Minh
7     19                 Ly Ly
8     20   Lý Nguyễn Trọng Tín
9     21       Nguyễn Hải Đăng

c:\Users\lmhai\anaconda3\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [53]:
items

    id_mon_an                    ten_mon_an
0          30                   Nước ép cam
1          31                   Nước ép dâu
2          35                       Nui xào
3          37                         Pepsi
4          39             Khoai lắc xí muội
5          42                  Combo cơm gà
6          43                  Combo Nhóm 1
7          44               Cơm Gà Xiên Que
8          46                  1 Bánh Trứng
9          48            2 Thanh Bí Phô Mai
10         49                  4 Bánh Trứng
11         50            5 Thanh Bí Phô Mai
12         51                       7Up Lon
13         52                Aquafina 500ml
14         53                       Trà Đào
15         54          Pepsi Black Lime Lon
16         55                      Milo Hộp
17         56               Mirinda Cam Lon
18         57                 Burger Zinger
19         58                    Burger Tôm
20         59          Burger Gà Quay Flava
21         60         Cơm Xiên Gà Tenderods
22         61               Cơm Gà Teriyaki
23         62                Cơm Gà Bít-tết
24         63         Gà Bít-tết với Khoai
25         64  Mì Ý Xốt Cà Xúc Xích Gà Viên
26         65            Mì Ý Xốt Gà Zinger
27         66                    Cơm Gà Rán
28         67            Cơm Phi-lê Gà Quay
29         68                  Miếng Gà Rán
30         69                2 Miếng Gà Rán
31         70                6 Miếng Gà Rán
32         71             Miếng Đùi Gà Quay
33         72               Miếng Phi-lê Gà
34         73           3 Cánh Gà Hot Wings
35         74           5 Cánh Gà Hot Wings
36         75                    3 Cá Thanh
37         76                    2 Xiên Que
38         77              2 Xiên Tenderods
39         78                4 Phô Mai Viên
40         79                6 Phô Mai Viên
41         80         3 Mashies Nhân Rau Củ
42         81         5 Mashies Nhân Rau Củ
43         82                 Súp Rong Biển
44         83                    Súp Rau Củ
45         84         Khoai Tây Chiên (Vừa)
46         85         Khoai Tây Chiên (Lớn)
47         86         Khoai Tây Chiên (Đại)
48         88        Khoai Tây Nghiền (Vừa)
49         89        Khoai Tây Nghiền (Lớn)
50         90        Khoai Tây Nghiền (Đại)
51         91                  Combo Nhóm 2
52         92                  Combo Nhóm 3
53         93                Combo Gia Đình

In [54]:
users

   id_kh                ten_kh
0      1        Nguyễn Văn Nam
1     13    Nguyễn Võ Khánh My
2     14  Nguyễn Võ Khánh Linh
3     15        Nguyễn Văn Anh
4     16       Nguyễn Khánh Ly
5     17             Lê Văn Bi
6     18     Nguyễn Hoàng Minh
7     19                 Ly Ly
8     20   Lý Nguyễn Trọng Tín
9     21       Nguyễn Hải Đăng

In [55]:
Ratings

                 ten_kh           ten_mon_an  diem_dg
0        Nguyễn Văn Nam          Nước ép dâu        5
1        Nguyễn Văn Nam    Khoai lắc xí muội        3
2        Nguyễn Văn Nam      Cơm Gà Xiên Que        1
3        Nguyễn Văn Nam       Aquafina 500ml        5
4        Nguyễn Văn Nam         Combo cơm gà        3
5        Nguyễn Văn Nam             Milo Hộp        4
6        Nguyễn Văn Nam         Combo Nhóm 1        5
7    Nguyễn Võ Khánh My  3 Cánh Gà Hot Wings        5
8    Nguyễn Võ Khánh My             Milo Hộp        5
9        Nguyễn Văn Anh       Aquafina 500ml        5
10       Nguyễn Văn Anh   2 Thanh Bí Phô Mai        4
11      Nguyễn Khánh Ly          Nước ép dâu        4
12      Nguyễn Khánh Ly                Pepsi        1
13      Nguyễn Khánh Ly          Nước ép cam        1
14      Nguyễn Khánh Ly         Combo Nhóm 1        5
15      Nguyễn Khánh Ly    Khoai lắc xí muội        3
16      Nguyễn Khánh Ly   2 Thanh Bí Phô Mai        4
17      Nguyễn Khánh Ly      Cơm Gà Xiên Que        5
18            Lê Văn Bi              7Up Lon        4
19            Lê Văn Bi   2 Thanh Bí Phô Mai        2
20    Nguyễn Hoàng Minh          Nước ép dâu        5
21                Ly Ly         Combo cơm gà        2
22                Ly Ly          Nước ép dâu        3
23  Lý Nguyễn Trọng Tín   2 Thanh Bí Phô Mai        5
24  Lý Nguyễn Trọng Tín              7Up Lon        5
25  Lý Nguyễn Trọng Tín    Khoai lắc xí muội        5
26  Lý Nguyễn Trọng Tín         4 Bánh Trứng        5
27  Lý Nguyễn Trọng Tín             Milo Hộp        3
28  Lý Nguyễn Trọng Tín                Pepsi        4
29  Lý Nguyễn Trọng Tín          Nước ép dâu        5
30  Lý Nguyễn Trọng Tín  3 Cánh Gà Hot Wings        5
31      Nguyễn Hải Đăng  3 Cánh Gà Hot Wings        5
32      Nguyễn Hải Đăng              7Up Lon        5

In [56]:
print(items.shape)
print(Ratings.shape)
print(users.shape)

(54, 2)
(33, 3)
(10, 2)

In [57]:
items.isnull().sum()

id_mon_an     0
ten_mon_an    0
dtype: int64

In [58]:
users.isnull().sum()

id_kh     0
ten_kh    0
dtype: int64

In [59]:
Ratings.isnull().sum()

ten_kh        0
ten_mon_an    0
diem_dg       0
dtype: int64

In [60]:
Ratings.duplicated().sum()

0

Hệ thống đề xuất dựa trên mức độ phổ biến

In [61]:
ratings_with_name = Ratings.merge(items, on='ten_mon_an')
# ratings_with_name = Ratings
ratings_with_name

                 ten_kh           ten_mon_an  diem_dg  id_mon_an
0        Nguyễn Văn Nam          Nước ép dâu        5         31
1       Nguyễn Khánh Ly          Nước ép dâu        4         31
2     Nguyễn Hoàng Minh          Nước ép dâu        5         31
3                 Ly Ly          Nước ép dâu        3         31
4   Lý Nguyễn Trọng Tín          Nước ép dâu        5         31
5        Nguyễn Văn Nam    Khoai lắc xí muội        3         39
6       Nguyễn Khánh Ly    Khoai lắc xí muội        3         39
7   Lý Nguyễn Trọng Tín    Khoai lắc xí muội        5         39
8        Nguyễn Văn Nam      Cơm Gà Xiên Que        1         44
9       Nguyễn Khánh Ly      Cơm Gà Xiên Que        5         44
10       Nguyễn Văn Nam       Aquafina 500ml        5         52
11       Nguyễn Văn Anh       Aquafina 500ml        5         52
12       Nguyễn Văn Nam         Combo cơm gà        3         42
13                Ly Ly         Combo cơm gà        2         42
14       Nguyễn Văn Nam             Milo Hộp        4         55
15   Nguyễn Võ Khánh My             Milo Hộp        5         55
16  Lý Nguyễn Trọng Tín             Milo Hộp        3         55
17       Nguyễn Văn Nam         Combo Nhóm 1        5         43
18      Nguyễn Khánh Ly         Combo Nhóm 1        5         43
19   Nguyễn Võ Khánh My  3 Cánh Gà Hot Wings        5         73
20  Lý Nguyễn Trọng Tín  3 Cánh Gà Hot Wings        5         73
21      Nguyễn Hải Đăng  3 Cánh Gà Hot Wings        5         73
22       Nguyễn Văn Anh   2 Thanh Bí Phô Mai        4         48
23      Nguyễn Khánh Ly   2 Thanh Bí Phô Mai        4         48
24            Lê Văn Bi   2 Thanh Bí Phô Mai        2         48
25  Lý Nguyễn Trọng Tín   2 Thanh Bí Phô Mai        5         48
26      Nguyễn Khánh Ly                Pepsi        1         37
27  Lý Nguyễn Trọng Tín                Pepsi        4         37
28      Nguyễn Khánh Ly          Nước ép cam        1         30
29            Lê Văn Bi              7Up Lon        4         51
30  Lý Nguyễn Trọng Tín              7Up Lon        5         51
31      Nguyễn Hải Đăng              7Up Lon        5         51
32  Lý Nguyễn Trọng Tín         4 Bánh Trứng        5         49

In [62]:
num_rating_df = ratings_with_name.groupby(
    'ten_mon_an').count()['diem_dg'].reset_index()
num_rating_df.rename(columns={'diem_dg': 'solandanhgia'}, inplace=True)
num_rating_df

             ten_mon_an  solandanhgia
0    2 Thanh Bí Phô Mai             4
1   3 Cánh Gà Hot Wings             3
2          4 Bánh Trứng             1
3               7Up Lon             3
4        Aquafina 500ml             2
5          Combo Nhóm 1             2
6          Combo cơm gà             2
7       Cơm Gà Xiên Que             2
8     Khoai lắc xí muội             3
9              Milo Hộp             3
10          Nước ép cam             1
11          Nước ép dâu             5
12                Pepsi             2

In [63]:
num_rating_df.shape

(13, 2)

In [64]:
avg_rating_df = ratings_with_name.groupby(
    'ten_mon_an').mean()['diem_dg'].reset_index()
avg_rating_df = avg_rating_df.rename(columns={'diem_dg': 'diemtb'})
avg_rating_df

             ten_mon_an    diemtb
0    2 Thanh Bí Phô Mai  3.750000
1   3 Cánh Gà Hot Wings  5.000000
2          4 Bánh Trứng  5.000000
3               7Up Lon  4.666667
4        Aquafina 500ml  5.000000
5          Combo Nhóm 1  5.000000
6          Combo cơm gà  2.500000
7       Cơm Gà Xiên Que  3.000000
8     Khoai lắc xí muội  3.666667
9              Milo Hộp  4.000000
10          Nước ép cam  1.000000
11          Nước ép dâu  4.400000
12                Pepsi  2.500000

In [65]:
popular_df = num_rating_df.merge(avg_rating_df, on='ten_mon_an')
popular_df

             ten_mon_an  solandanhgia    diemtb
0    2 Thanh Bí Phô Mai             4  3.750000
1   3 Cánh Gà Hot Wings             3  5.000000
2          4 Bánh Trứng             1  5.000000
3               7Up Lon             3  4.666667
4        Aquafina 500ml             2  5.000000
5          Combo Nhóm 1             2  5.000000
6          Combo cơm gà             2  2.500000
7       Cơm Gà Xiên Que             2  3.000000
8     Khoai lắc xí muội             3  3.666667
9              Milo Hộp             3  4.000000
10          Nước ép cam             1  1.000000
11          Nước ép dâu             5  4.400000
12                Pepsi             2  2.500000

In [66]:
popular_df.duplicated().sum()

0

In [67]:
popular_df.shape

(13, 3)

In [68]:
items.head(1)

   id_mon_an   ten_mon_an
0         30  Nước ép cam

In [69]:
popular_df = popular_df[popular_df['solandanhgia'] >
                        0].sort_values('diemtb', ascending=False).head(50)
popular_df

             ten_mon_an  solandanhgia    diemtb
1   3 Cánh Gà Hot Wings             3  5.000000
2          4 Bánh Trứng             1  5.000000
4        Aquafina 500ml             2  5.000000
5          Combo Nhóm 1             2  5.000000
3               7Up Lon             3  4.666667
11          Nước ép dâu             5  4.400000
9              Milo Hộp             3  4.000000
0    2 Thanh Bí Phô Mai             4  3.750000
8     Khoai lắc xí muội             3  3.666667
7       Cơm Gà Xiên Que             2  3.000000
6          Combo cơm gà             2  2.500000
12                Pepsi             2  2.500000
10          Nước ép cam             1  1.000000

In [70]:
popular_df = popular_df.merge(items, on='ten_mon_an').drop_duplicates('ten_mon_an')[
    ['id_mon_an', 'ten_mon_an', 'solandanhgia', 'diemtb']]
popular_df

    id_mon_an           ten_mon_an  solandanhgia    diemtb
0          73  3 Cánh Gà Hot Wings             3  5.000000
1          49         4 Bánh Trứng             1  5.000000
2          52       Aquafina 500ml             2  5.000000
3          43         Combo Nhóm 1             2  5.000000
4          51              7Up Lon             3  4.666667
5          31          Nước ép dâu             5  4.400000
6          55             Milo Hộp             3  4.000000
7          48   2 Thanh Bí Phô Mai             4  3.750000
8          39    Khoai lắc xí muội             3  3.666667
9          44      Cơm Gà Xiên Que             2  3.000000
10         42         Combo cơm gà             2  2.500000
11         37                Pepsi             2  2.500000
12         30          Nước ép cam             1  1.000000

In [71]:
popular_df

    id_mon_an           ten_mon_an  solandanhgia    diemtb
0          73  3 Cánh Gà Hot Wings             3  5.000000
1          49         4 Bánh Trứng             1  5.000000
2          52       Aquafina 500ml             2  5.000000
3          43         Combo Nhóm 1             2  5.000000
4          51              7Up Lon             3  4.666667
5          31          Nước ép dâu             5  4.400000
6          55             Milo Hộp             3  4.000000
7          48   2 Thanh Bí Phô Mai             4  3.750000
8          39    Khoai lắc xí muội             3  3.666667
9          44      Cơm Gà Xiên Que             2  3.000000
10         42         Combo cơm gà             2  2.500000
11         37                Pepsi             2  2.500000
12         30          Nước ép cam             1  1.000000

Hệ thống đề xuất dựa trên bộ lọc cộng tác

In [72]:
x = ratings_with_name.groupby('ten_kh').count()['diem_dg'] >= 0
padhe_likhe_users = x[x].index
x.sum()
# padhe_likhe_users

9

In [73]:
filtered_rating = ratings_with_name[ratings_with_name['ten_kh'].isin(
    padhe_likhe_users)]

In [74]:
y = filtered_rating.groupby('ten_mon_an').count()['diem_dg'] > 0
famous_books = y[y].index
int(y.sum())

13

In [75]:
final_ratings = filtered_rating[filtered_rating['ten_mon_an'].isin(
    famous_books)]

In [76]:
# final_ratings['ten_kh']

In [77]:
pt = final_ratings.pivot_table(
    index='ten_kh', columns='ten_mon_an', values='diem_dg')

In [78]:
data= pt
data

ten_mon_an,2 Thanh Bí Phô Mai,3 Cánh Gà Hot Wings,4 Bánh Trứng,7Up Lon,Aquafina 500ml,Combo Nhóm 1,Combo cơm gà,Cơm Gà Xiên Que,Khoai lắc xí muội,Milo Hộp,Nước ép cam,Nước ép dâu,Pepsi
ten_kh,,,,,,,,,,,,,
Ly Ly,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,3.0,NaN
Lê Văn Bi,2.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lý Nguyễn Trọng Tín,5.0,5.0,5.0,5.0,NaN,NaN,NaN,NaN,5.0,3.0,NaN,5.0,4.0
Nguyễn Hoàng Minh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
Nguyễn Hải Đăng,NaN,5.0,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Nguyễn Khánh Ly,4.0,NaN,NaN,NaN,NaN,5.0,NaN,5.0,3.0,NaN,1.0,4.0,1.0
Nguyễn Võ Khánh My,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN
Nguyễn Văn Anh,4.0,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Nguyễn Văn Nam,NaN,NaN,NaN,NaN,5.0,5.0,3.0,1.0,3.0,4.0,NaN,5.0,NaN

In [79]:
item = list(data.columns)

In [80]:
user = list(data.index)

In [81]:
data_matrix = data[item[0:]].fillna(0).values
# data_matrix

In [82]:
Sim = cosine_similarity(data_matrix, data_matrix)
Sim = np.round(Sim, decimals=2)
# Sim

In [83]:
pd.DataFrame(Sim, columns=user, index=user)

,Ly Ly,Lê Văn Bi,Lý Nguyễn Trọng Tín,Nguyễn Hoàng Minh,Nguyễn Hải Đăng,Nguyễn Khánh Ly,Nguyễn Võ Khánh My,Nguyễn Văn Anh,Nguyễn Văn Nam
Ly Ly,1.00,0.00,0.31,0.83,0.00,0.35,0.00,0.00,0.56
Lê Văn Bi,0.00,1.00,0.51,0.00,0.63,0.19,0.00,0.28,0.00
Lý Nguyễn Trọng Tín,0.31,0.51,1.00,0.38,0.53,0.46,0.43,0.24,0.37
Nguyễn Hoàng Minh,0.83,0.00,0.38,1.00,0.00,0.41,0.00,0.00,0.48
Nguyễn Hải Đăng,0.00,0.63,0.53,0.00,1.00,0.00,0.50,0.00,0.00
Nguyễn Khánh Ly,0.35,0.19,0.46,0.41,0.00,1.00,0.00,0.26,0.58
Nguyễn Võ Khánh My,0.00,0.00,0.43,0.00,0.50,0.00,1.00,0.00,0.27
Nguyễn Văn Anh,0.00,0.28,0.24,0.00,0.00,0.26,0.00,1.00,0.37
Nguyễn Văn Nam,0.56,0.00,0.37,0.48,0.00,0.58,0.27,0.37,1.00

In [84]:
def predict(A, u, i, k=2):
    user_rated_i = np.where(A[:, i] != 0)[0]
    sim = Sim[u, user_rated_i]
    a = (np.argsort(sim))[-k:]
    nearest_s = sim[a]
    rating = A[user_rated_i[a], i]
    r_bar = (rating*nearest_s).sum()/(np.abs(nearest_s).sum())
    return np.round(r_bar, 2)

In [85]:
predict_matrix = data_matrix.copy()
for u in range(0, predict_matrix.shape[0]):
  for i in range(0, predict_matrix.shape[1]):
    if data_matrix[u, i] == 0:
      id = i
      predict_matrix[u, i] = predict(data_matrix, u, id)
# predict_matrix

C:\Users\lmhai\AppData\Local\Temp\ipykernel_12864\4069319877.py:7: RuntimeWarning: invalid value encountered in double_scalars
  r_bar = (rating*nearest_s).sum()/(np.abs(nearest_s).sum())

In [86]:
pd.DataFrame(predict_matrix, columns=item[0:], index=user)

,2 Thanh Bí Phô Mai,3 Cánh Gà Hot Wings,4 Bánh Trứng,7Up Lon,Aquafina 500ml,Combo Nhóm 1,Combo cơm gà,Cơm Gà Xiên Que,Khoai lắc xí muội,Milo Hộp,Nước ép cam,Nước ép dâu,Pepsi
Ly Ly,4.47,5.0,5.0,5.00,5.0,5.0,2.00,2.54,3.00,3.64,1.0,3.00,2.41
Lê Văn Bi,2.00,5.0,5.0,4.00,5.0,5.0,NaN,5.00,4.46,3.00,1.0,4.73,3.19
Lý Nguyễn Trọng Tín,5.00,5.0,5.0,5.00,5.0,5.0,2.54,3.22,5.00,3.00,1.0,5.00,4.00
Nguyễn Hoàng Minh,4.48,5.0,5.0,5.00,5.0,5.0,2.37,2.84,3.00,3.56,1.0,5.00,2.44
Nguyễn Hải Đăng,3.37,5.0,5.0,5.00,NaN,NaN,NaN,NaN,5.00,3.97,NaN,5.00,4.00
Nguyễn Khánh Ly,4.00,5.0,5.0,4.71,5.0,5.0,2.62,5.00,3.00,3.56,1.0,4.00,1.00
Nguyễn Võ Khánh My,5.00,5.0,5.0,5.00,5.0,5.0,3.00,1.00,4.23,5.00,NaN,5.00,4.00
Nguyễn Văn Anh,4.00,5.0,5.0,4.46,5.0,5.0,3.00,2.65,3.00,3.61,1.0,4.59,2.44
Nguyễn Văn Nam,4.00,5.0,5.0,5.00,5.0,5.0,3.00,1.00,3.00,4.00,1.0,5.00,2.17